export const STATIC_POKEMON_CARDS = [
  {
    "id": 906,
    "name": "Sprigatito",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/906.png",
    "types": ["grass"],
    "attack": 310,
    "defense": 290,
    "hp": 550,
    "specialAbility": "Overgrow",
    "level": "Común",
    "description": "Desprende un dulce aroma al frotar sus patas delanteras, capaz de cautivar a cualquiera que esté a su alrededor."
  },
  {
    "id": 909,
    "name": "Fuecoco",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/909.png",
    "types": ["fire"],
    "attack": 320,
    "defense": 300,
    "hp": 580,
    "specialAbility": "Blaze",
    "level": "Común",
    "description": "Se tumba sobre rocas cálidas para absorber el calor del sol a través de sus escamas y convertirlo en fuego."
  },
  {
    "id": 912,
    "name": "Quaxly",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/912.png",
    "types": ["water"],
    "attack": 300,
    "defense": 280,
    "hp": 560,
    "specialAbility": "Torrent",
    "level": "Común",
    "description": "Sus plumas secretan un gel brillante y repelente al agua que le permite deslizarse a gran velocidad por el agua."
  },
  {
    "id": 908,
    "name": "Meowscarada",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/908.png",
    "types": ["grass", "dark"],
    "attack": 510,
    "defense": 350,
    "hp": 760,
    "specialAbility": "Overgrow",
    "level": "Épica",
    "description": "Utiliza flores cargadas de polen explosivo y desvía la atención de sus enemigos mediante ilusiones mágicas."
  },
  {
    "id": 911,
    "name": "Skeledirge",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/911.png",
    "types": ["fire", "ghost"],
    "attack": 550,
    "defense": 450,
    "hp": 850,
    "specialAbility": "Blaze",
    "level": "Épica",
    "description": "Su canto melodioso activa el pájaro de fuego espectral que habita sobre su hocico para quemar a sus oponentes."
  },
  {
    "id": 914,
    "name": "Quaquaval",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/914.png",
    "types": ["water", "fighting"],
    "attack": 520,
    "defense": 400,
    "hp": 800,
    "specialAbility": "Torrent",
    "level": "Épica",
    "description": "Ejecuta bailes tradicionales exóticos y propina patadas espectaculares capaces de quebrar troncos de acero."
  },
  {
    "id": 921,
    "name": "Pawmi",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/921.png",
    "types": ["electric"],
    "attack": 250,
    "defense": 220,
    "hp": 450,
    "specialAbility": "Static",
    "level": "Común",
    "description": "Tiene sacos de electricidad en sus mejillas y frota sus patas contra ellas para lanzar descargas eléctricas."
  },
  {
    "id": 923,
    "name": "Pawmot",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/923.png",
    "types": ["electric", "fighting"],
    "attack": 460,
    "defense": 380,
    "hp": 780,
    "specialAbility": "Static",
    "level": "Rara",
    "description": "Acomula gran cantidad de energía estática en sus palmas para liberar golpes eléctricos de alta tensión."
  },
  {
    "id": 926,
    "name": "Fidough",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/926.png",
    "types": ["fairy"],
    "attack": 220,
    "defense": 350,
    "hp": 520,
    "specialAbility": "Own-tempo",
    "level": "Común",
    "description": "Su piel elástica tiene una textura suave de levadura. Cuando se altera, se hincha para amedrentar a su rival."
  },
  {
    "id": 936,
    "name": "Armarouge",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/936.png",
    "types": ["fire", "psychic"],
    "attack": 480,
    "defense": 420,
    "hp": 820,
    "specialAbility": "Flash-fire",
    "level": "Rara",
    "description": "Viste una armadura imbuida de energía psíquica y dispara bolas de fuego ardientes desde sus hombreras."
  },
  {
    "id": 937,
    "name": "Ceruledge",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/937.png",
    "types": ["fire", "ghost"],
    "attack": 520,
    "defense": 380,
    "hp": 790,
    "specialAbility": "Flash-fire",
    "level": "Rara",
    "description": "Sus espadas espectrales arden con las llamas del rencor. Corta a sus enemigos absorbiendo su energía vital."
  },
  {
    "id": 957,
    "name": "Tinkatink",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/957.png",
    "types": ["fairy", "steel"],
    "attack": 240,
    "defense": 320,
    "hp": 480,
    "specialAbility": "Mold-breaker",
    "level": "Común",
    "description": "Golpea trozos de chatarra con su martillo de fabricación casera y lucha con valentía para defenderse."
  },
  {
    "id": 959,
    "name": "Tinkaton",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/959.png",
    "types": ["fairy", "steel"],
    "attack": 490,
    "defense": 440,
    "hp": 850,
    "specialAbility": "Mold-breaker",
    "level": "Épica",
    "description": "Blande un enorme martillo de metal de más de 100 kg. Derriba a los Corviknight voladores lanzándoles rocas."
  },
  {
    "id": 964,
    "name": "Palafin",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/964.png",
    "types": ["water"],
    "attack": 580,
    "defense": 410,
    "hp": 900,
    "specialAbility": "Water-veil",
    "level": "Rara",
    "description": "Al escuchar los lamentos de sus aliados, se transforma al instante en un héroe delfín de fuerza incalculable."
  },
  {
    "id": 1007,
    "name": "Koraidon",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1007.png",
    "types": ["fighting", "dragon"],
    "attack": 680,
    "defense": 520,
    "hp": 1350,
    "specialAbility": "Orichalcum-pulse",
    "level": "Legendaria",
    "description": "Una criatura ancestral descrita en libros antiguos. Su fuerza física descomunal le permite hender montañas."
  },
  {
    "id": 1008,
    "name": "Miraidon",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1008.png",
    "types": ["electric", "dragon"],
    "attack": 680,
    "defense": 520,
    "hp": 1350,
    "specialAbility": "Hadron-engine",
    "level": "Legendaria",
    "description": "Un enigmático Pokémon del futuro lejano. Despide ráfagas eléctricas de alta tecnología mediante sus motores."
  }
];
